#!/usr/bin/env node
/**
 * Bundle page-qr.src.js (+ the qrcode encoder) into a single self-contained
 * script and drop it into every property's public/js/.
 *
 * Two of the thirteen properties (Levinese, Joscha) live outside this monorepo
 * and cannot import the @soma/feedback workspace package, so the vendored-file
 * route is the only shape that is identical on all of them. Same precedent as
 * the vendored soma-feedback CSS/JS already in those repos.
 *
 *   node packages/feedback/src/page-qr/build.mjs            # all properties
 *   node packages/feedback/src/page-qr/build.mjs karl-friston hub
 */
import { build } from 'esbuild'
import { readdirSync, existsSync, mkdirSync, writeFileSync, statSync } from 'node:fs'
import { join, dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const REPO = resolve(HERE, '../../../..')
const HOME = process.env.HOME

// Properties outside this monorepo. They get the identical file.
const EXTERNAL = [
  { slug: 'levinese', dir: join(HOME, 'Projects/Levinese') },
  { slug: 'joschese', dir: join(HOME, 'Projects/Joscha') },
]

function targets(filter) {
  const list = [{ slug: 'hub', dir: join(REPO, 'hub') }]

  for (const name of readdirSync(join(REPO, 'sites'))) {
    const dir = join(REPO, 'sites', name)
    if (name.startsWith('_') || !statSync(dir).isDirectory()) continue
    // Stub dirs hold harvested papers only — no Astro site to carry a widget.
    if (!existsSync(join(dir, 'src/layouts/Base.astro'))) continue
    list.push({ slug: name, dir })
  }

  for (const ext of EXTERNAL) {
    if (existsSync(ext.dir)) list.push(ext)
    else console.warn(`  ! skipped ${ext.slug} — ${ext.dir} not found`)
  }

  return filter.length ? list.filter((t) => filter.includes(t.slug)) : list
}

const result = await build({
  entryPoints: [join(HERE, 'page-qr.src.js')],
  bundle: true,
  minify: true,
  format: 'iife',
  target: ['es2019'],
  platform: 'browser',
  legalComments: 'none',
  write: false,
})

const banner =
  '/* soma-page-qr — GENERATED. Source: agi-2026/packages/feedback/src/page-qr/page-qr.src.js\n' +
  '   Rebuild: node packages/feedback/src/page-qr/build.mjs — do not edit this file. */\n'
const code = banner + result.outputFiles[0].text

const chosen = targets(process.argv.slice(2))
for (const t of chosen) {
  const outDir = join(t.dir, 'public/js')
  mkdirSync(outDir, { recursive: true })
  writeFileSync(join(outDir, 'soma-page-qr.js'), code)
  console.log(`  ✓ ${t.slug}`)
}
console.log(`\n${chosen.length} properties · ${(code.length / 1024).toFixed(1)} KB each`)
